DjangoTemplateGammer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include(('TempGama.urls', 'TempGama'), namespace='temp')),
    path('test2/', include(('mytest.urls', 'mytest'), namespace='mytest')),
    # path('mytemp/', include(('Mytemplate.urls', 'Mytemplate'), namespace='mytemp')),
]

TempGama/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from TempGama import views

urlpatterns = [
    path('', views.index_handler, name='index'),
    path('t1', views.t1_handler, name='t1'),
    path('t2', views.t2_handler, name='t2'),
    path('t3', views.t3_handler, name='t3'),
    path('t4', views.t4_handler, name='t4'),
    #反向解析
    re_path('re/(\d+)', views.re_handler, name='re'),
    # 过滤器
    path('t5',views.t5_handler,name='t5'),
    path('blog',views.blog_handler,name='blog')
]

mytest/urls.py
from django.urls import path, re_path

from mytest import views

urlpatterns = [
    path('', views.test_handler, name='index'),
    path('index',views.name_handler,name='index2'),
    path('t1',views.t1_handler,name='t1'),
    path('t2',views.t2_handler,name='t2'),
    path('t3',views.t3_handler,name='t3'),
    #反向解析
    re_path('re/(\d+)',views.re_handler,name='re'),
    path('t4',views.t4_handler,name='t4'),
    # 过滤器
    path('t5',views.t5_handler,name='t5'),
    path('blog',views.blog_handler,name='blog'),
]

TempGama/models.py
from django.db import models

# Create your models here.

mytest/models.py
from django.db import models

# Create your models here.

TempGama/views.py
import datetime

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index_handler(request):
    return HttpResponse('TempGama.index')


def t1_handler(request):
    result = {
        'key1':'value1',
        'key2':['value1','value2'],
        'key3':{
            'key3_1':'value3_1',
            'key3_2':'value3_2'
        }
    }
    return render(request,'t1.html',result)


def t2_handler(request):
    context ={
        'hobbys': ['java','jpython','dokor']
    }
    return render(request,'t2.html',context)


def t3_handler(request):
    context = {
        'message':'这是一个有思思的句子',
        'style':0
    }
    return render(request,'t3.html',context)


def t4_handler(request):
    return render(request,'t4.html')


def re_handler(request,num):
    return HttpResponse(num)

def t5_handler(request):
    context ={
        'html_code': '<a href="//www.edu.csdn.net">CSDN学院</a>',
        'datetime':datetime.now()
    }
    return render(request,'t5.html',context)


def blog_handler(request):
    return render(request,'blog.html')

mytest/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def test_handler(request):
    return render(request,'index.html')


def name_handler(request):
    context = {
        'username':'name1',
        'password':'12345'
    }
    return render(request,'index1.html',context)


def t1_handler(request):
    context= {
        'key1':'value1',
        'key2':['value1','value2'],
        'key3':{'key3_1':'value3_1','key3_2':'value3_2'},
    }
    return render(request,'t1.html',context)


def t2_handler(request):
    context={
        'hobbys':['java','python','c++']
    }
    return render(request,'t2.html',context)


def t3_handler(request):
    context = {
        'style':2,
        'message':'这是会变色的文章'
    }
    return render(request,'t3.html',context)


def t4_handler(request):
    return render(request,'t4.html')


def re_handler(request,num):
    return HttpResponse(num)


def t5_handler(request):
    context ={
        'html_code': '<a href="//www.edu.csdn.net">CSDN学院</a>',
        'datetime':datetime.now()
    }
    return render(request,'t5.html',context)


def blog_handler(request):
    return render(request,'blog.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客</title>
    <style type="text/css">
        *{ padding:0px; margin:0px; text-decoration: none; color:black; font-weight:normal; font-size:16px; }
        header{ width:1400px; margin:20px auto; padding:0px 0px 10px 0px; border-bottom: 1px solid darkgrey; }
        header>div{ display:block; width:1200px; margin:auto; }
        header span{ display:inline-block; text-align: center; margin:0px 100px; font-size:18px; }
        article{ width:1000px; margin:auto; padding:20px 100px; border-right:1px solid darkgrey; border-left:1px solid darkgrey; }
        footer{ width:1400px; border-top:1px solid darkgrey; margin:20px auto; }
        footer>div{ width:400px; margin:20px; float: right;}
        h1{ font-weight: bold; padding:0px 0px 20px 0px; }
        p{ text-indent: 2em; }
        li{ padding:10px; }
    </style>
</head>
<body>
<header>
    <div>
        <span><a href="#">首页</a></span>
        <span><a href="#">我的博客</a></span>
        <span><a href="#">管理博客</a></span>
        <span><a href="#">联系我们</a></span>
    </div>
</header>

<article>
    {% block article %}
    <ul>
        <li>我的博客1|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客2|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客3|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客4|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客5|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客6|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客7|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客8|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客9|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客10|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客11|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客12|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客13|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客14|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客15|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客16|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客17|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
        <li>我的博客18|发行日期：2019-07-20 00:00:00|阅读人数：999人</li>
    </ul>
    {% endblock %}
</article>
<footer>
    <div>
        <table>
            <tr>
                <td>邮箱:</td>
                <td>XXXXXXXXX@qq.com</td>
            </tr>
            <tr>
                <td>电话:</td>
                <td>18866668888</td>
            </tr>
        </table>
    </div>
</footer>
</body>
</html>

templates/blog.html
{% extends 'base.html' %}

{% block article %}
    重写的内容
{#    {{ block.super }}#}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello</title>
</head>
<body>
    hello,its my django template
</body>
</html>

templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    hello templates
    <br/>
    用户名：{{ username }}
    <br/>
    密码：{{ password }}


</body>
</html>

templates/t1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>t1</title>
</head>
<body>
{# 1.普通值获取 #}
	{{ key1 }}
	<br/>
{# 2.列表值获取 #}
	{{ key2.0}} {{ key2.1 }}
	<br/>
{# 3.字典值获取 #}
	{{ key3.key3_1 }}  {{ key3.key3_2 }}

</body>
</html>

templates/t2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>t1</title>
</head>
<body>
{% for hobby in hobbys %}
	爱好：{{ hobby }}<br/>
{% endfor %}
</body>
</html>

templates/t3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>t1</title>
</head>
<body>
{% if style == 0 %}
    <span style="color:red">{{ message }}</span>
{% elif style == 1 %}
    <span style="color:blue">{{ message }}</span>
{% else %}
    <span style="color:green">{{ message }}</span>
{% endif %}
</body>
</html>

templates/t4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>t1</title>
</head>
<body>
mytest:
<ul>
    <li>
        index_handler的地址是：{% url 'mytest:index' %}
    </li>
    <li>
        re_handler的地址是：{% url 'mytest:re' 2%}
    </li>
</ul>
</body>
</html>

templates/t5.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>t5</title>
</head>
<body>
原样输出：
<ul>
    <li>html_code:{{ html_code }}</li>
    <li>datetime:{{ datetime }}</li>
</ul>
过滤器：（格式：变量|过滤器:参数）
<ul>
    <li>safe禁止转义：{{ html_code|safe }}</li>
    <li>length：{{ html_code|length }}</li>
    <li>date输出日期：{{ datetime|date:'Y-m-d H:i:s' }}</li>
    <li>default默认值：{{ style|default:'默认值' }}</li>
    <li>upper转大写：{{ html_code|upper }}</li>
    <li>lower转小写：{{ html_code|lower }}</li>
    <li>多个过滤器：{{ html_code|lower|safe }}</li>
</ul>

</body>
</html>